### ISSUE TITLE
"Phantom" calls to rest one / tap gesture

### ISSUE THREAD

**Issue by ab1470** [rxhanson/Multitouch-Bugs#30]
I'm getting a lot of "phantom" calls to the "Rest one finger and tap one finger to the left/right" gesture. It probably has something to do with the way I rest my fingers on the trackpad, but I never had the same problem with Jitouch, even though I had the same gestures configured to do the same thing (tab switching). Perhaps Jitouch was somehow rejecting false input that Multitouch is not rejecting.

**Comment by rxhanson** [comment]
Thanks for letting me know. In v1.8.1 that just went out (https://multitouch.app/versions), I made it so that the two fingers must be closer together in order to execute. I believe this is how JiTouch works, but I haven't thoroughly tested it to know for sure. If you're still having issues, then this could be more due to resting thumb/palm rejection. That's more difficult to get right, but I have some things I could try out if needed.

**Comment by ab1470** [comment]
Thanks, but 1.8.1 doesn't seem to have fixed it. After trying to reproduce the problem, I've found that it's not due to a thumb or palm rejection issue. It happens even when I deliberately keep my thumb and palm away from the trackpad. 

I think the issue for me is that I often either rest two fingers on the trackpad, or hover them just barely above it. Multitouch seems to be registering some of the light touches I do as I move between hovering and touching the trackpad as rest/tap gestures. Are there some tweaks you can make so that it picks up only the deliberate rest/tap gestures, while rejecting other touches?

**Comment by rxhanson** [comment]
Ok, that makes sense. There are some tweaks I can put in place for this.

A little background on why you would experience this: Multitouch was originally written without using Apple's private Multitouch framework. It just obtained the touch data as gesture events from an event tap. There's pros and cons to each way to obtain touch data, but a major disadvantage of going with only the event tap route is that you don't get a lot of details about each touch, particularly the size. The major advantage to avoiding the private framework is that Apple might change it or stop allowing 3rd parties to use it at any point. I've since incorporated using the private framework by default in Multitouch, but have built all of my trackpad gestures to survive in case the private framework gets yanked. With all that said, I'll add in some better touch detection using the private framework that should fix what you're experiencing. As a side note, it looks to me like the other main gesture apps (JiTouch, MagicPrefs, BTT) were all built from the start using the private framework, so this is why you'll notice some differences with Multitouch.

**Comment by rxhanson** [comment]
In [v1.8.3](https://multitouch.app/versions), I've added in a filter that rejects "light touches". Hopefully, you'll see improvements out of the box with this.

If you're still having issues, the filter value is configurable. The numbers are pretty arbitrary, but they can be configured via user defaults and you can try out different values as needed.
The default value I use is 0.4, and I would recommend going up or down by 0.1 increments. A higher number means larger touches will be ignored. Here's the command:

defaults write com.brassmonkery.Multitouch filterLightTouches -float 0.4

If you have a value that works really well for you, feel free to let me know and I can use that to help figure out an ideal default value.

**Comment by lorenzofanchi** [comment]
This happens to me occasionally when two-finger scrolling. The scroll will lead to triggering a 'one fix +tap' gesture.

**Comment by rxhanson** [comment]
@lorenzofanchi Thanks for the details. When you tap with two fingers to stop the scroll at a specific point, did your fingers come off of the trackpad entirely for the scroll before they touched back for the tap to stop the scroll? Not saying that you need to change what you're doing, it would just help to see if there's an issue with the way I am identifying touches.

**Comment by lorenzofanchi** [comment]
@rxhanson yes, they do. I 'flick' to scroll, then tap to stop scrolling

**Comment by lorenzofanchi** [comment]
@rxhanson three finger tap is also getting harder to trigger since v1.8.3. This seems to be related to the tap gesture sensitivity setting, as 'resting' my three fingers longer on the trackpad before lifting them up, seems to increase the trigger rate. Strangely, the one fix, tap left/right seem to require much lighter taps, as I don't have any trouble getting these to trigger anymore..

**Comment by rxhanson** [comment]
@lorenzofanchi The tap gesture settings should be pretty much identical to what was there prior to v1.8.3, the only thing that changed was the display of the settings. Previously, there were five notches on the slider, these would be 1, 2, 3, 4, and 5. Now easy corresponds to 4, med corresponds to 3, and hard corresponds to 2. I realize that 2 is just not enjoyable to use, so the next release will change this again so that "Low" sensitivity is 3, "Med" is 4, and "High" is 5, although there's not a huge difference between 4 and 5. 

You're right in that there is a longer resting time required for a _harder_ or _lower sensitivity_ setting. 

There were no changes in recent releases that would have affected the difficulty of executing the three finger tap, but it could just be a nature of the gesture taking into account slightly more variables than the one plus tap gesture, like the finger movement of each finger. I don't mind revisiting the three tap - it's been a while since I've looked at it, but it will take me a little while to get around to it. 

Also, I have a fix for the one plus tap getting executed when you scroll, but I was going to wait to drop a release until I include some more fixes. If it takes too long for me to get something out, I'll drop a quick minor release for you to try it out.

**Comment by lorenzofanchi** [comment]
Thanks for pushing a new version out. I'm still having issues though...

With Swipe gesture sensitivity set to **High**, I now trigger One Fixed + Swipe Up and Down gestures while scrolling. When I set Swipe gesture sensitivity to **Medium** I can't get swipe actions to trigger altogether, or at least not without trying _really_ hard... One fixed, two finger swipes would solve this, IMO.

**Comment by rxhanson** [comment]
Sorry for the delayed response. Hope you guys have had a good start to the new year.

There's still a bit more I can do to try to fix this issue, but I'll add the rest one, swipe two to my backlog. I'm looking to wind down the new gesture additions, as I feel like the set that I have is already more than scratching my itch for what I personally would want in a gesture app. Really, the only gestures left that I will consider (for now at least) is multi finger swipe in each direction, and rest one swipe two. As you know, I don't really like the idea of conflicting with Apple's gestures, but these gestures have been regularly asked for. Unfortunately, I don't quite have the time to devote to Multitouch for a little while, so I can't promise these gestures real soon. Multi finger swipe in each direction has been asked for by a lot of people, so I'll probably look at that one first when I get the time again.

Thanks for continuously testing and providing feedback on these issues, @ab1470 & @lorenzofanchi. I'll post again when I get some time to dig into this again.

**Comment by lorenzofanchi** [comment]
This is still the biggest issue I have with Multitouch :( would be great to see this resolved..

**Comment by rxhanson** [comment]
By nature of the gesture, the rest one tap one is a little too easy for me to execute in normal use, even on JiTouch, but I'm willing to dig into this a bit more. Rest one tap one / rest one swipe one gestures are, unfortunately, by far the most difficult gestures to get consistent across trackpads and users. This feels like it could be a rabbit hole of endless tweaking, which, needless to say would eat into time spent on other gestures/features. If you were to rank this vs rest one swipe two (or something else), which would you rather have?

**Comment by lorenzofanchi** [comment]
I think I'd rather have swipe three left/right (and up/down). Seems like that could solve most issues in one go AND enable some more customization :)

**Comment by rxhanson** [comment]
Sounds good, that'll be next to go in. I'll push rest one tap one further down the backlog.

**Comment by yooyoyo** [comment]
rest one finger and tap to left or right seems to work just perfect with jiTouch but with Multitouch I am having few problems like 
1. many times it will require 2 to 3 taps just to get to another tab which is very annoying but when gestures work it is smooth
2. sometimes instead of switching tabs it will play the background video 

I tried to play with settings but it made it worse and I feel like I have to tap pretty firmly to make the gestures work.
Also I would say that most people use 2 fingers on their trackpad and this feature is a must for me atleast. 
Which gesture you use to switch your tabs if not this one?

**Comment by rxhanson** [comment]
@yooyoyo, I created a different issue with your post since it's not the same as this issue. 
https://github.com/Brass-Monkery/Multitouch-Bugs/issues/42

**Comment by rxhanson** [comment]
As per the original thread on this issue, I am making some changes to the rest one tap one that should hopefully fix the inadvertent triggering on scroll. This will get rolled out in the next release (beta or official).

**Comment by lorenzofanchi** [comment]
@rxhanson looking forward to this! Any chance of a beta build to test? I'd like to re-instate my fix one, tap one gestures for tab switching, but the inadvertent triggering has been holding me back..

**Comment by rxhanson** [comment]
@lorenzofanchi my initial work on this is in [v1.11.2](https://multitouch.app/versions), which includes the change that should (hopefully) prevent the accidental execution after stopping scroll. 

I still have some changes to make - specifically that gestures like this one can be accidentally triggered by my resting thumb rejection code when using the private multi-touch framework.

**Comment by rxhanson** [comment]
@lorenzofanchi, I've added [v1.11.3](https://multitouch.app/versions) that contains more changes on this behavior. If you get a chance to try it out, please let me know if it fixes this or not. 

There's one more piece that I'm thinking of adding in - detecting if all touches leave the trackpad immediately after this gesture gets triggered, thereby preventing the gesture from executing. Since this could make the gesture feel a little laggy depending on how long it's necessary to wait, I'll have to see how it feels as to whether or not it's worth doing or with a setting for enabling/disabling this behavior.

As a somewhat related aside, in v1.11.3, I've replaced the "Tap Sensitivity" setting with "Touch Precision". I never really liked the behavior I implemented in "Tap Sensitivity", so this is an attempt to fix it. This setting will default to high and you shouldn't have to make any changes to it. I'm planning on writing a blog post providing the gritty details about it.

**Comment by lorenzofanchi** [comment]
@rxhanson thanks! I was still able to trigger the behavior using 1.11.2, so I'm curious to see if this fixes the issue once and for all!

**Comment by rxhanson** [comment]
@lorenzofanchi, there is actually one other variable I can make configurable that would affect accidental triggering of rest one tap one, and it's the duration of time that the resting touch must be present. This variable is kind of delicate - to me it made the gesture feel too hard to execute when I increased it, but I'll do a good bit more testing and see exactly how much increase I can get away with. I'll also make it configurable in 1.11.4. It's moot if your testing of 1.11.3 is good, but if you want to wait for 1.11.4, that's ok too. Thanks!

**Comment by rxhanson** [comment]
@lorenzofanchi v1.11.4 is up on the versions page. You can set the resting touch holding time using 
`defaults write com.brassmonkery.Multitouch restingHoldTime -float <time in seconds>
`
Originally it was set to 0.2 seconds. I've upped it to 0.33. If you find a value that works best for you, let me know and that'll help me decide on a default value. 
I believe this and the other changes that I've made should resolve this issue, but if the problem still exists even with all of this, then I'll look into adding the check for touches leaving the device immediately after the gesture is executed.

**Comment by rxhanson** [comment]
@lorenzofanchi, I decided to go ahead and add the check for touches leaving the device immediately after the gesture is executed. From my testing, I feel like this is the change that should finally fix the issue - perhaps this is the first change I should have made long ago. I've put this change in a beta (v1.13.1). Similar to the resting touch holding time, I've made this a configurable variable (gestureEndCancelTime). When a rest plus tap is performed, the app waits this specified time before executing the configured action. If the touches leave the device before the time is up, then the action does not get executed. You can configure it with this command, followed by restarting the app: 
`defaults write com.brassmonkery.Multitouch gestureEndCancelTime -float <time in seconds>`
I have it default to 0.08 (80ms). This felt right to me, since it's a bit too quick to be humanly noticeable, but long enough to catch stray touches that might result in an accidental execution.
Let me know if you get a chance to try it out and if it seems to work for you or not, or if you change this value at all to something that does work. Fingers crossed this one's done.

**Comment by lorenzofanchi** [comment]
This sounds great! I just installed the beta and will test as much as possible! 👍

**Comment by rxhanson** [comment]
Doing some housekeeping and closing out old issues. If phantom rest one tap ones are still an issue, we can reopen it.
