### ISSUE TITLE
debug logging

### ISSUE THREAD

**Issue by lorenzofanchi** [rxhanson/Multitouch-Bugs#44]
Is there any way to get an option to enable debug logging? I'm getting some weird behavior every once in a while (apps starting seemingly randomly, spaces switching without me knowingly triggering it) and would like to see if multitouch is maybe triggering them. @rxhanson Any other ideas how I could troubleshoot?

Thanks!

**Comment by rxhanson** [comment]
There is and there isn't debug logging...
I use OS Logging, which logs straight to the console, but it does not display values of variables when the app is run outside of the Xcode debugger.
You'll be able to see if gestures are triggering, but you won't be able know which one it is.

1. Open Console.app. 
1. Type "Gesture matched" without quotes into the search bar.
1. In the Action menu, select Include Debug Messages.

Let me know if you narrow it down, and it is Multitouch causing problems. Since a lot of the recent changes revolve around gesture sensitivity, it wouldn't be a huge surprise to me if gestures are getting triggered accidentally.

Improved debug logging with information about touches is something that's in my queue for the next release, but I suspect you'll figure out any gestures causing issues before I get that out.

**Comment by rxhanson** [comment]
I've noticed some buggy behavior with gestures triggering unexpectedly, and I'm pretty sure I know what's causing it - should have a fix out soon.

**Comment by rxhanson** [comment]
I went ahead and released a new version that fixes a bug introduced in v1.12, and it might fix the problem that you're seeing. I wanted to go ahead and get it out the door, so I didn't add the improved debug logging yet. Still in the works for next release though.

**Comment by lorenzofanchi** [comment]
That's great, thanks a lot! It's been a very intermittent issue, so it'll probably take a while for me to figure out if it's really fixed or not (or if it's caused by another app). Thanks!

**Comment by lorenzofanchi** [comment]
I think I just had a ghost trigger, so maybe not fixed yet. Will try to keep the Console open to monitor triggering..

**Comment by rxhanson** [comment]
Ok, thanks for letting me know. I put up a new beta v1.13.3 that has a small change to the logging that will now include the name of the gesture executed for you. I still plan on getting just better logging out the door, but at least this should help you out in the meantime since it could take a little while to complete the better logging task properly.

**Comment by rxhanson** [comment]
Just doing some housekeeping, closing out issues. I don't have plans to add in more debug logging than what's currently in there at this time, which is mainly just logging when gestures are triggered. For really complicated issues, it eventually means rolling custom debug builds, and that's kind of the nature of the app since it doesn't make sense to have conditionals for logging spread throughout the entire app.
