### ISSUE TITLE
Rest one finger and tap right/left

### ISSUE THREAD

**Issue by yooyoyo** [rxhanson/Multitouch-Bugs#56]
this feature works only when I space my finger really apart - this is not usually how I use the trackpad....When I place my 2 fingers at a wider distance it recognises almost all the taps but for my normal usage it will click and tap or just won't respond...Is there any way I can tweak this in the settings or can you help me with this???

**Comment by rxhanson** [comment]
There's nothing in the rest one tap one algorithm that is dependent on how close the touches are together, so there's nothing that can be tweaked in that regard. The only values that can be tweaked there are very specific to timing, and it's not going to help you to change those if you already have the timing down with the wider spacing. 

This could be something specific to your machine or how you perform the gesture. Since there's not really anything that makes sense to tweak and it's the type of issue that can't really be solved in a reasonable amount of time, I don't mind giving you a full refund if you are not satisfied with the app - just send an email to support@multitouch.app with the email address you used to purchase it. Thanks.
