### ISSUE TITLE
Add text paste action

### ISSUE THREAD

**Issue by Risengan** [rxhanson/Multitouch-Bugs#60]

**Comment by rxhanson** [comment]
This is already in Multitouch, but it's hard to find. My plan is to change up the structuring of actions so that it's easier to find.
Under "Keypress", the first item is "Custom Keyboard Shortcut", where you can record the keyboard shortcut for paste (typically cmd+v).

Closing this one out, but feel free to reopen or comment if this doesn't solve your issue.

**Comment by Risengan** [comment]
I meant the ability to paste a particular text (configured in Multitouch) like email address, not the current clipboard

**Comment by rxhanson** [comment]
Ah, ok. I like it. Reopening.

**Comment by rxhanson** [comment]
This can now be done via a new keystroke recorder in v1.17, currently in pre-release on https://multitouch.app/versions. Let me know if you try it out.

**Comment by Risengan** [comment]
I noted some problems: The pasted text is in capital letters and the special characters do not seem to be displayed. Another thing (?), the text seems to appear letter by letter.
<img width="1142" alt="Capture d’écran 2020-03-09 à 20 20 22" src="https://user-images.githubusercontent.com/11879201/76249630-09cdc580-6244-11ea-95af-4d806c7ea633.png">

**Comment by rxhanson** [comment]
Thanks for testing this out and letting me know! 

The text appears letter by letter because the keystroke recorder is actually recording your keypresses and playing them back as keystrokes when you execute the action. The reason that I implemented it this way is because Apple limits what you can do globally. I do have access to the pasteboard, but loading the pasteboard and pasting text (ctrl v) takes an unknown amount of time. Not knowing when the paste is done makes it so re-loading your pasteboard with what was in there before a guessing game for when to do it. This leads to a pretty weird user experience if you happen to paste really quickly after executing this action. So, we're at the alternative of having a recorder that actually implements the keypresses. I only tested with lowercase words (sorry!). I think this is something that can be fixed with adding some human-unnoticeable delay, but obviously we'd still have individual keypresses that would be susceptible to altered behavior with modifiers held like the shift key. I'll post back when I have something else up.

**Comment by rxhanson** [comment]
Also, my @ sign seems to work just fine... What keyboard layout are you using?

**Comment by rxhanson** [comment]
Ok, I did have a bug in there - no delays were necessary to fix what I had.

https://multitouch.app/downloads/multitouch1.17.1.dmg

Let me know what you find when you test this one out.

Side note, these keypresses are actually not susceptible to being altered by modifier keys being held during the execution, as I incorrectly guessed in a previous comment.

**Comment by Risengan** [comment]
Hi! 👋 
It works, the characters are case-sensitive with version 17.1! 🙂
I use an AZERTY (FR) keyboard.

**Comment by rxhanson** [comment]
After using the DeepL app, I noticed it uses the paste action that I mentioned not wanting to use, and it actually does it quite nicely. Going to close out this issue, but I'm thinking I'll probably add the paste version of this in at some point.

**Comment by rxhanson** [comment]
Alright, paste text action is now in v1.17.9.

**Comment by garethhance** [comment]
@rxhanson - have you considered extending the paste option to include a text only function? I'm using Pure Paste  by Sindre Sohrus to cut & paste between Word & ChatGPT. by default text from Word into ChatGPT gets pasted as an image. The workaround is ChatGPT does some OCR, use an interim step like notepad or an app like Pure Paste. I've got Pure Paste set to paste as text only on a keystroke, Alt+Cmd+V. Doesn't seem out of context to include this functionality in Multipaste.

**Comment by rxhanson** [comment]
@garethhance Are you simply looking for paste without formatting (option+shift+cmd+V)?

![image](https://github.com/user-attachments/assets/969287a5-b20c-4f78-b6f8-3d159a15ad60)

Or are you looking for something more involved?
