### ISSUE TITLE
Boom 2 hide app

### ISSUE THREAD

**Issue by cotfas** [rxhanson/Multitouch-Bugs#66]
Multitouch: 1.17.4 (84)
macOS: Version 10.15.4 (Build 19E266)
Model: MacBookPro14,2
Devices: ["magicMouse:288230378114662828:1962951084","internalTrackpad2:144115188092633088:16777216"]
Multitouch Configuration: [{"gid":{"gesture":"oneClickTopRight"},"r":{"type":2,"action":205}},{"gid":{"gesture":"onePlusLeftMouse"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"twoPlusLeftMouse"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"onePlusRight"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"twoLeftEdgeSwipe"},"r":{"type":12}},{"gid":{"gesture":"fourForce"},"r":{"type":15,"action":1501}},{"gid":{"gesture":"oneForce"},"r":{"type":3,"action":300}},{"gid":{"gesture":"oneClickBottomRight"},"r":{"type":2,"action":206}},{"gid":{"gesture":"oneClickTopLeft"},"r":{"type":2,"action":208}},{"gid":{"gesture":"onePlusLeft"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"oneClickBottomLeft"},"r":{"type":2,"action":209}},{"gid":{"gesture":"oneForceBottomRight"},"r":{"type":1,"keyCode":45,"modifierFlags":1048576}},{"gid":{"gesture":"fourClick"},"r":{"type":15,"action":1504}},{"gid":{"gesture":"oneForceTopRight"},"r":{"type":2,"action":214}},{"gid":{"gesture":"fourTap"},"r":{"type":15,"action":1503}}]
Avoid Private Framework: false

Boom2 4 finger touchpad click (not force click, not tap), does not hide the app. 

PS: The app does not have dock icon.

**Comment by rxhanson** [comment]
The hide action executes the keyboard shortcut for hiding an app. It's up to the app to implement the hiding behavior, which is typically standard for all mac apps. If you try executing the keyboard shortcut for hide with Boom2 in front, you'll notice that it doesn't hide because this behavior was not implemented in the app. My suggestion is to file a bug with the Boom2 developers to see if they will implement it.
