### ISSUE TITLE
Provide levels of haptic feedback

### ISSUE THREAD

**Issue by cotfas** [rxhanson/Multitouch-Bugs#68]
I`ve noticed the 'Provide haptic feedback' and is nice :)

It is working, will be nice to provide some levels of feedback (1-4), 1 should be ok with the current implementation, 4 - a little bit lower than the click feedback

*Noticed the 4 levels in the https://github.com/pigigaldi/Pock app

**Comment by rxhanson** [comment]
Ok, I got a chance to look into this one. The ability to provide different levels of feedback is only attainable by using the private Multitouch framework. If you uncheck the box for Avoid private framework in the Multitouch app, it will use this same private framework that provides this functionality, but too many users reported that gestures randomly stop registering when the private framework is used. Since I can't recommend users to uncheck that box, I wouldn't be able to recommend this feature. Unfortunately it doesn't make sense to add it in with that pretense. It also isn't worth it to have the private framework run for a trackpad only for this feature and have the rest of the trackpad data consumed through the supported framework, as sometimes just listening to anything via the private trackpad can cause issues. It's touchy and I've been burned by it enough.

This is disappointing for me, as I agree that this would be a great feature, and I'd like the current feedback to be greater. Thanks for the suggestion though!
