### ISSUE TITLE
Restart on wake issue

### ISSUE THREAD

**Issue by cotfas** [rxhanson/Multitouch-Bugs#69]
Some of the times the "restart on wake" does not work.

Some of the times I reopen the mac lid and the Multitouch app is closed, not sure what is the scenario.

Catalina latest with Multitouch 1.17.4(84)

**Comment by poislagarde** [comment]
I'm also having issues with restart on wake on my MBP 16".

The app doesn't seem to close / restart by itself and my gestures stop working after sleeping. I have to close and reopen the app manually every time.

**Comment by cotfas** [comment]
I have disabled the "restart on wake" option and will see how it goes.

In the meantime hopefully I get some feedback from Karabiner (https://github.com/pqrs-org/Karabiner-Elements/issues/2241) and will use the corners clicks/force click to create a script for reopening the app if closed.

**Comment by poislagarde** [comment]
BTW I'm on macOS 10.15.4 (19E287) and Multitouch v1.17.4 (84)

**Comment by rxhanson** [comment]
@cotfas thanks for filing this. Please try v1.17.7. You can get it via in-app update or at https://multitouch.app/versions

Let me know if you still experience this problem with v1.17.7.

**Comment by rxhanson** [comment]
@poislagarde Your issue might be a little different, but there is a slight chance it could also be fixed by v1.17.7.

If that doesn't fix it, a couple of things: Are you sure that it is not restarting at all on wake (provided that you have the checkbox checked)? 

If it is restarting on wake, let's try increasing the amount of time the app waits before restarting itself. There's a macOS glitch that few users have reported where macOS won't provided gesture input to the app if it starts listening too soon. You can increase the amount of time the app waits with the following terminal command:

`defaults write com.brassmonkery.Multitouch restartOnWakeDelay -int 10`

The default value is 2. At the very least, setting this should allow you to visibly see that the app is closed and reopened. Then, if we still have issues we can dig a little deeper. Let me know when you get a chance to try it and what you find out.

**Comment by poislagarde** [comment]
@rxhanson v1.17.7 by itself didn't fix it, but setting restartOnWakeDelay to 10 seems to do the trick 🥳. I'll play around with lower values and report back.

**Comment by cotfas** [comment]
So far I see no issue, but will keep you posted. (enabled "wake on rr")

**Comment by rxhanson** [comment]
@poislagarde let me know if you find a setting that works for you. If it's pretty low, maybe it makes sense to adjust the default value in Multitouch.

@cotfas thanks for following up. Just as a note on the restart on wake setting - from what I can tell most users don't actually need that setting enabled. I don't personally have it enabled and I've never had issues with macOS providing touch input to the app on wake. It seems to affect only specific devices, and typically it seems to be older MacBook Airs. So, if things work fine without having it enabled then it's ok to disable it. I had enough users come across issues that I made it enabled by default in a previous release.

**Comment by cotfas** [comment]
Alright, I will use it disabled for a while to see.

**Comment by poislagarde** [comment]
@rxhanson the lowest value I could get it working consistently is 4. I used 3 for a while but every now and then I had to restart manually. So far, 4 is working great.

Thanks for the help!

**Comment by rxhanson** [comment]
@poislagarde I appreciate that you reported back! Thanks.

I'm going to close out this issue, but feel free to reopen or comment again if there's issues with restart on wake.
