### ISSUE TITLE
Gestures do not work when the trackpad is turned off

### ISSUE THREAD

**Issue by ammnt** [rxhanson/Multitouch-Bugs#71]
Hello,

Today I reinstated macos and set up gestures (three fingers tap for center window and four fingers tap for maximize window). But they do not work after turning off the built-in trackpad in the accessibility settings, although it was not the case before. It is bug or now it can`t be works like before?
```
Multitouch: 1.17.16 (96)
macOS: Version 10.15.5 (Build 19F101)
Model: MacBookPro14,1
Devices: ["internalTrackpad2:144115188092633088:16777216","magicMouse:288230377408548859:1256837115"]
Multitouch Configuration: [{"gid":{"gesture":"threeTap"},"r":{"type":15,"action":1517}},{"gid":{"gesture":"fourTap"},"r":{"type":15,"action":1507}}]
```
Thank you.
Best regards!

**Comment by rxhanson** [comment]
Hi, thanks for reporting. To fix this in Multitouch, all you have to do is uncheck the box for "Avoid private framework" in the settings tab of the preferences window. This will prompt the app to restart.

I changed the default behavior on a fresh install of Multitouch to not use the private framework where possible because it is typically more stable to avoid it, but most users don't see any stability issues while using the private framework.

**Comment by ammnt** [comment]
> Hi, thanks for reporting. To fix this in Multitouch, all you have to do is uncheck the box for "Avoid private framework" in the settings tab of the preferences window. This will prompt the app to restart.
> 
> I changed the default behavior on a fresh install of Multitouch to not use the private framework where possible because it is typically more stable to avoid it, but most users don't see any stability issues while using the private framework.

Yeah, it wokrs perfect now! Thank you, sir!🤝
