### ISSUE TITLE
Unable to open Discord after having used "Close window under cursor"

### ISSUE THREAD

**Issue by vincchan** [rxhanson/Multitouch-Bugs#75]
After having used "Close window under cursor" by invoking through Three Finger Gesture "Rest one finger and swipe down with two to the right" to close Discord Window, it is unable to be reopened again.
<img width="561" alt="Screenshot 2020-11-13 at 14 54 35" src="https://user-images.githubusercontent.com/868272/99079569-6c8c1380-25c0-11eb-91ba-5b2347b5659a.png">

macOS BigSur
Multitouch v1.19.5 (111)

1. Open Discord
2. Close using Gesture
3. Try opening Discord again (unable to show window)

**Comment by rxhanson** [comment]
Thanks for reporting.

To close a window, Multitouch use the accessibility API to execute the close functionality tied to the close button on the window. Since Discord's window behaves differently when closed this way vs being closed by actually clicking on the close button, then that means that the Discord developers are performing different functionality when the click occurs.

There's not really a better way to close a window of another app than using the Accessibility API, which means that it's unfortunately outside of the scope of the Multitouch to fix this bug. Apologies for the inconvenience, but the best path forward is to file an issue with Discord.
